### ISSUE TITLE
How to install debian？

### ISSUE THREAD

**Issue by sunqiangcn** [ecmendenhall/wgif#20]
help me Please

**Comment by ecmendenhall** [comment]
I'm happy to help, but I need a little more information about what went wrong. Do you have any error output you can share?

Debian/Ubuntu stopped shipping with ffmpeg in favor of a forked version called [libav](https://lwn.net/Articles/650816/). I'd guess that's the likeliest issue: you'll have to install ffmpeg from a [third-party `.deb` repository](https://superuser.com/questions/286675/how-to-install-ffmpeg-on-debian) or [compile it from source](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu).
