### ISSUE TITLE
No such file or directory - ffmpeg -i /tmp/wgif/1A78yTvIY1k

### ISSUE THREAD

**Issue by suptoiret** [ecmendenhall/wgif#21]
Hi
I'm trying to run wgif on ubuntu but every video I try even the borjk video gives me an error like this:

Something went wrong creating your GIF. The details:

No such file or directory - ffmpeg -i /tmp/wgif/1A78yTvIY1k
/usr/lib/ruby/1.9.1/open3.rb:202:in `spawn'
/usr/lib/ruby/1.9.1/open3.rb:202:in `popen_run'
/usr/lib/ruby/1.9.1/open3.rb:90:in `popen3'
/var/lib/gems/1.9.1/gems/streamio-ffmpeg-1.0.0/lib/ffmpeg/movie.rb:17:in `initialize'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/video.rb:10:in `new'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/video.rb:10:in `initialize'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/video_cache.rb:12:in `new'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/video_cache.rb:12:in `get'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/downloader.rb:34:in `get_video'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/cli.rb:43:in `convert_video'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/cli.rb:19:in `block in make_gif'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/cli.rb:56:in `rescue_errors'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/lib/wgif/cli.rb:17:in `make_gif'
/var/lib/gems/1.9.1/gems/wgif-0.5.2/bin/wgif:4:in `<top (required)>'
/usr/local/bin/wgif:23:in `load'
/usr/local/bin/wgif:23:in `<main>'

Please open an issue at: https://github.com/ecmendenhall/wgif/issues/new

I have checked and I have the folder /tmp/wgif/ with files like 1A78yTvIY1k so I don't understand because this says that It doesn't find that file and finish in this way.

Thanks

**Comment by ecmendenhall** [comment]
Do you have ffmpeg installed? (It wasn't included by default in Ubuntu 14). What is the result of `which ffmpeg`?
