### ISSUE TITLE
Build error. What do I need to install first?

### ISSUE THREAD

**Issue by jimkang** [ecmendenhall/wgif#9]
When I try to install the gem via `sudo gem install wgif`, I get an error while it's building native extensions:

`clang: error: unknown argument: '-multiply_definedsuppress' [-Wunused-command-line-argument-hard-error-in-future]`

I'm on Mavericks, with Xcode 5 and ruby 2.0.0p247. Do I need to install some dependency first? [Here's the whole install log.](https://gist.github.com/jimkang/9678825#file-gistfile1-txt-L194)

**Comment by ecmendenhall** [comment]
I'm going to close this: I think this issue was specific to XCode 5 and later and Ruby 2.0.0-p247. This issue was fixed in 2.0.0p451 and the latest OS X system ruby is 2.0.0p481. Feel free to reopen it if you're still having trouble!

**Comment by jimkang** [comment]
Thanks for your diligence! I had moved on from the project I wanted this for but meant to come back to this issue. Terribly sorry that I didn't!
